repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black

  - repo: local
    hooks:
      - id: check-migrations
        name: Check Alembic Migrations
        entry: python backend/scripts/check_migrations.py
        language: python
        types: [python]
        pass_filenames: false
        additional_dependencies: [alembic]
