"""add content hash

Revision ID: 2c71c52a2da3
Revises: remove_hash_constraint
Create Date: 2025-05-19 12:18:27.618773

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c71c52a2da3"
down_revision: Union[str, None] = "remove_hash_constraint"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column as nullable first
    op.add_column("events", sa.Column("content_hash", sa.String(), nullable=True))

    # Update existing rows to have the same hash as the event hash
    op.execute("UPDATE events SET content_hash = hash WHERE content_hash IS NULL")

    # Make the column non-nullable
    op.alter_column("events", "content_hash", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "content_hash")
    # ### end Alembic commands ###
