"""add stripe signing secret

Revision ID: 8b92bccd8308
Revises: 2c71c52a2da3
Create Date: 2025-05-19 12:35:38.544318

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8b92bccd8308"
down_revision: Union[str, None] = "2c71c52a2da3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tenants", sa.Column("stripe_signing_secret", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenants", "stripe_signing_secret")
    # ### end Alembic commands ###
