---
name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Backend tests
        run: |
          pip install poetry
          cd backend
          poetry install --no-root
          poetry run pytest -v
      - name: Frontend tests
        run: |
          cd frontend && yarn install --frozen-lockfile && yarn test
